name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: self-hosted
    steps:
      - name: Echo the message
        if: ${{ github.event_name == 'push' }} 
        run: |
          echo "Hola midudevs! ${{secrets.HEROKU_API_KEY}} 2 - PRUEBAS SELF-HOSTED"
      - name: Dime la fecha
        run: date
      - run: ls -l