name: Deployment Pipeline

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Build
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      - name: Test  
        run: npm test
      - name: teste2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000